// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/CTA.tsx";
import * as $$$$$$1 from "./sections/Features.tsx";
import * as $$$$$$2 from "./sections/Footer.tsx";
import * as $$$$$$4 from "./sections/HackaAbout.tsx";
import * as $$$$$$5 from "./sections/HackaAgent.tsx";
import * as $$$$$$3 from "./sections/HackaAITech.tsx";
import * as $$$$$$6 from "./sections/HackaFAQ.tsx";
import * as $$$$$$7 from "./sections/HackaFooter.tsx";
import * as $$$$$$8 from "./sections/HackaFormat.tsx";
import * as $$$$$$9 from "./sections/HackaHero.tsx";
import * as $$$$$$10 from "./sections/HackaIdeas.tsx";
import * as $$$$$$11 from "./sections/HackaMCP.tsx";
import * as $$$$$$12 from "./sections/HackaPrizes.tsx";
import * as $$$$$$13 from "./sections/HackaRegistration.tsx";
import * as $$$$$$14 from "./sections/HackaSponsors.tsx";
import * as $$$$$$15 from "./sections/HackaWhoIsItFor.tsx";
import * as $$$$$$16 from "./sections/Hero.tsx";
import * as $$$$$$17 from "./sections/Integrations.tsx";
import * as $$$$$$18 from "./sections/ItWorks.tsx";
import * as $$$$$$19 from "./sections/ReCAPTCHA.tsx";
import * as $$$$$$20 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/CTA.tsx": $$$$$$0,
    "site/sections/Features.tsx": $$$$$$1,
    "site/sections/Footer.tsx": $$$$$$2,
    "site/sections/HackaAbout.tsx": $$$$$$4,
    "site/sections/HackaAgent.tsx": $$$$$$5,
    "site/sections/HackaAITech.tsx": $$$$$$3,
    "site/sections/HackaFAQ.tsx": $$$$$$6,
    "site/sections/HackaFooter.tsx": $$$$$$7,
    "site/sections/HackaFormat.tsx": $$$$$$8,
    "site/sections/HackaHero.tsx": $$$$$$9,
    "site/sections/HackaIdeas.tsx": $$$$$$10,
    "site/sections/HackaMCP.tsx": $$$$$$11,
    "site/sections/HackaPrizes.tsx": $$$$$$12,
    "site/sections/HackaRegistration.tsx": $$$$$$13,
    "site/sections/HackaSponsors.tsx": $$$$$$14,
    "site/sections/HackaWhoIsItFor.tsx": $$$$$$15,
    "site/sections/Hero.tsx": $$$$$$16,
    "site/sections/Integrations.tsx": $$$$$$17,
    "site/sections/ItWorks.tsx": $$$$$$18,
    "site/sections/ReCAPTCHA.tsx": $$$$$$19,
    "site/sections/Theme/Theme.tsx": $$$$$$20,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
